db_user     = "admin"
db_password = "adminpassword"
db_name     = "mydatabase"
minio_access_key = "minioadmin"
minio_secret_key = "minioadmin"
rabbitmq_user     = "admin"
rabbitmq_password = "adminpassword"